config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :tasks do
    member do
      patch :complete
    end
  end
  root 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  def completed?
    !completed_at.blank?
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:show, :edit, :update, :destroy, :complete]

  def index
    if user_signed_in?
      @tasks = Task.where(:user_id => current_user.id).order("created_at DESC")
    end
  end

  def show
  end

  def new
    @task = current_user.tasks.build
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to task_path(@task)
    else
      render 'edit'
    end
  end

  def destroy
    @task.destroy
    redirect_to root_path
  end

  def complete
    @task.update_attribute(:completed_at, Time.now)
    redirect_to root_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :description)
  end

  def find_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hiptime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Hiptime", root_path, class:"navbar-brand" %>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user.present? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Log In", new_user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% end %>
        </ul>
        <% if user_signed_in? %>
          <%= link_to "Create Task", new_task_path, class: "navbar-text navbar-link" %>
        <% end %>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <%= yield %>
    </div>


  </body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for @task do |f| %>
  <%= f.input :title, label: "Task Title" %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/tasks/_welcome_page.html.erb
<div class="jumbotron">
  <h2>HipTime! Free and Easy.</h2>
  <br>
  <h4>Trusted by Millions. HipTime is the best online Task Management App!</h4>
  <br>
  <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-danger" %>
</div>

app/views/tasks/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1>Edit Todo Task</h1>

  <%= render 'form' %>
</div>

app/views/tasks/index.html.erb
<!-- Checks to see if a user is signed in, if one is, it will list its checklist. -->
<!-- If not, it will render the landing page that asks the user to sign up or login. -->
<% if user_signed_in? %>
  <div class="col-md-10 col-md-offset-1">
    <% @tasks.each do |task| %>
      <div class="index-wrapper">

        <% if task.completed? %>
<!-- For Completed Tasks-->
          <div class="row item">

            <div class="col-md-2">
              <p><%= link_to complete_task_path(task), method: :patch do %></p>
                <i class="fa fa-check fa-lg"></i>
              <% end %>
            </div>

            <div class="col-md-2">
              <p><%= link_to task, method: :delete, data: { confirm: "Are you sure?" } do %></p>
                <i class="fa fa-trash fa-lg"></i>
              <% end %>
            </div>

            <div class="col-md-8">
              <h2 style="opacity: 0.5;" class="task-title"><strike><%= link_to task.title, task %></strike></h2>
              <p style="opacity: 0.5;" class="task-sub-title task-desc"><%= task.description %></p>
              <p style="opacity: 0.5;" class="time-created-at task-sub-title">Completed <%= time_ago_in_words(task.completed_at) %> ago</p>
            </div>

          </div>

        <% else %>
<!-- For Tasks NOT Completed -->

          <div class="row item">

            <div class="col-md-2">
              <p><%= link_to complete_task_path(task), method: :patch do %></p>
                <i class="fa fa-check fa-lg"></i>
              <% end %>
            </div>

            <div class="col-md-8">
              <h2 class="task-title"><%= link_to task.title, task %></h2>
              <p class="task-sub-title task-desc"><%= task.description %></p>
              <p style="opacity: 0.5;" class="time-created-at task-sub-title">Created <%= time_ago_in_words(task.created_at) %> ago</p>
            </div>

            <div class="col-md-2">
              <p><%= link_to task, method: :delete, data: { confirm: "Are you sure?" } do %></p>
                <i class="fa fa-trash fa-lg"></i>
              <% end %>
            </div>
          </div>

        <% end %>
      </div>
    <% end %>
  </div>

<% else %>
  <%= render 'welcome_page' %>
<% end %>

app/views/tasks/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1>New Todo Task</h1>

  <%= render 'form' %>
</div>

app/views/tasks/show.html.erb
<div class="col-md-10 col-md-offset-1">
  <h2><%= @task.title %></h2>
  <p><%= @task.description %></p>

  <div class="col-md-4 col-md-offset-4">
    <%= link_to "Back", root_path %>
    <%= link_to "Edit", edit_task_path %>
  </div>
</div>